# Generated by Django 4.0.5 on 2022-06-25 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('empresa', models.CharField(max_length=200)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('respondida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('interesse', models.CharField(max_length=100)),
                ('forma_contato', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('respondida', models.BooleanField(default=False)),
            ],
        ),
    ]
